sudo: false
language: ruby
rvm:
  - 2.4.1
services:
  - mysql
  - postgresql
before_install:
  - gem install bundler -v 1.15.4
before_script:
  - cp spec/fixtures/shards.yml.travis spec/fixtures/shards.yml
  - rake db:test:prepare
after_success:
  - bundle exec codeclimate-test-reporter
